### PR TITLE
Added Magnific popup for lightbox images

### PR DESCRIPTION
**Pull request by dapsych0**

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks so smuch @dapsych0 - this is awesome! I'm trying to learn in the process to be able to do this myself next time.

After testing it, I have a question: the current setting is to have the image zooming it as pop-up when one clicks on it and stays clicked. The default behavior I'd like to have for all posts is the one called "Lightbox gallery" on the pulgin's demo: https://dimsemenov.com/plugins/magnific-popup/ 

How can we switch it on? I guess there is something to change in `_layouts/`? (https://github.com/OGGM/oggm.github.io/blob/master/_layouts/)

**Comment by dapsych0** [comment]
The click to zoom effect was provided by the code in imagezoom.html - but I removed that file from the pages so you don't get that. With this pull request, it now creates a lightbox gallery with the images on the page, as per your own blog.

**Comment by fmaussion** [comment]
Oh right! Tested the wrong branch :roll_eyes: - OK let's get this in and see if it works

**Comment by dapsych0** [comment]
@fmaussion You will need to fix some blog posts, such as https://oggm.org/2019/05/04/OGGM-paper/ as the images are not links, and dont have the correct style... This blog post is good: https://oggm.org/2019/06/21/4st-oggm-worshop-summary/  
Youll need to make images links and add the width="100%" to the img tag

**Comment by fmaussion** [comment]
@dapsych0 I see! Will review all posts now - thanks a lot your help this is much appreciated :+1:

**Pull request merged**
